# Generated by Django 4.0.5 on 2022-07-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ojApp', '0002_rename_problem_id_submission_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
