# Generated by Django 4.0.5 on 2022-07-07 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ojApp', '0003_rename_user_id_submission_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submission',
            new_name='submissions',
        ),
    ]
