# Generated by Django 4.0.5 on 2022-07-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojApp', '0009_alter_problems_test_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='expected_output',
            field=models.FileField(null='True', upload_to='oj_expected_outputs<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='test_cases',
            field=models.FileField(null='True', upload_to='oj_test_cases<django.db.models.fields.CharField>/'),
        ),
    ]
