# Generated by Django 4.0.5 on 2022-07-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ojApp', '0011_alter_problems_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='user_name',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
